version: '3.8'
services:
  social-media-stats:
    image: ghcr.io/l4ma/website-social-media-stats:latest
    container_name: social-media-stats
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 