name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Clear npm cache
      run: npm cache clean --force
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false --passWithNoTests
      
    - name: Build application
      run: npm run build
      
    - name: Test Docker build
      run: |
        docker build -t social-media-stats-test .
        # Test that the image was built successfully
        docker images | grep social-media-stats-test
        # Test that the container can start (don't wait for health check in CI)
        docker run --rm --name test-container social-media-stats-test nginx -t 