name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Convert repository name to lowercase
      id: repo
      run: |
        echo "repo_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ steps.repo.outputs.repo_lowercase }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test the published image
      run: |
        docker pull ghcr.io/${{ steps.repo.outputs.repo_lowercase }}:latest
        docker run --rm ghcr.io/${{ steps.repo.outputs.repo_lowercase }}:latest wget --quiet --tries=1 --spider http://localhost/health || exit 1
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🚀 Social Media Statistics Dashboard v${{ github.ref_name }}
          
          ### 📦 Docker Image
          ```bash
          # Pull the image
          docker pull ghcr.io/${{ steps.repo.outputs.repo_lowercase }}:${{ github.ref_name }}
          
          # Run the container
          docker run -d -p 3000:80 ghcr.io/${{ steps.repo.outputs.repo_lowercase }}:${{ github.ref_name }}
          
          # Access the application
          open http://localhost:3000
          ```
          
          ### 🐳 Docker Compose
          ```yaml
          version: '3.8'
          services:
            social-media-stats:
              image: ghcr.io/${{ steps.repo.outputs.repo_lowercase }}:${{ github.ref_name }}
              ports:
                - "3000:80"
              restart: unless-stopped
          ```
          
          ### ✨ What's New
          - Docker image published to GitHub Container Registry
          - Optimized build process
          - Health check endpoint
          - Production-ready configuration
          
          ### 📊 Features
          - YouTube statistics integration
          - Instagram demo data
          - Interactive charts and filters
          - Modern responsive UI
          
          ### 🔗 Links
          - **GitHub Repository**: https://github.com/${{ github.repository }}
          - **Docker Image**: ghcr.io/${{ steps.repo.outputs.repo_lowercase }}:${{ github.ref_name }}
          - **Documentation**: https://github.com/${{ github.repository }}/blob/main/README.md
        draft: false
        prerelease: false 